app/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name="index"),
    url(r'^curso\/?$', RedirectView.as_view(url='cursos', permanent=False), name='redirect_curso'),
    url(r'^cursos\/?$', views.CursoList.as_view(), name="curso_list"),
    url(r'^curso/(?P<slug>\S+)$', views.CursoDetalle.as_view(), name="curso_detalle"),
    url(r'^registrarse\/?$', views.Registrarse.as_view(), name="registrar"),
    url(r'^registrarse_post\/?$', views.RegistrarsePost, name="registrar_post"),
    url(r'^crear_cohorte\/?$', views.CrearCohorte, name="crear_cohorte"),
    url(r'^activar_lt\/?$', views.ActivarLT, name="activar_lt"),
    url(r'^mis_cursos\/?$', views.CursosLT.as_view(), name="mis_cursos"),
    url(r'^mis_notas/(?P<pk>\d+)$', views.MisNotas, name="mis_notas"),
    url(r'^actividad/(?P<pk>\d+)$', views.ActividadDetalle, name="actividad"),
    url(r'^certificados\/?$', views.Certificados, name="certificados"),
    url(r'^reportes\/?$', views.Reportes, name="reportes"),
    url(r'^reporte1\/?$', views.Reporte1, name="reporte1"),
    url(r'^reporte2\/?$', views.Reporte2, name="reporte2"),
    url(r'^reporte3\/?$', views.Reporte3, name="reporte3"),
    url(r'^reporte4\/?$', views.Reporte4, name="reporte4"),
    url(r'^reporte5\/?$', views.Reporte5, name="reporte5"),
    url(r'^reporte6\/?$', views.Reporte6, name="reporte6"),
    url(r'^reporte7\/?$', views.Reporte7, name="reporte7"),
    url(r'^reporte8\/?$', views.Reporte8, name="reporte8"),
    url(r'^reporte9\/?$', views.Reporte9, name="reporte9"),
    url(r'^mis_cursosmt\/?$', views.CursosMT.as_view(), name="mis_cursosmt"),
    url(r'^calificar\/?$', views.ProcesarCalificacion, name="calificar"),
    url(r'^calificar/(?P<pk>\d+)$', views.CalificarListaAct, name="calificar_lista"),
    url(r'^calificar/(?P<pk>\d+)/(?P<idact>\d+)$', views.CalificarActividad, name="calificar_actividad"),
)

ciersur/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
	url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/', include("django_markdown.urls")),
    url(r'^', include('app.urls')),
]

app/models.py
# -*- coding:Utf-8 -*-
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import MaxValueValidator, MinValueValidator


class CierUserManager(BaseUserManager):
    def create_user(self, id_persona, tipo, 
                    password=None):
        if not tipo:
            raise ValueError('Users must have a type')
        persona = Persona.objects.get(cedula=id_persona)
        user = self.model(id_persona=persona,tipo=tipo)
        user.set_password(password)
        return user

    def create_superuser(self, id_persona, tipo,
                         password):
        user = self.create_user(id_persona, tipo, 
                                password=password)
        user.tipo = 1
        user.is_admin = True
        user.save()
        return user


class Persona(models.Model):
    cedula = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    correo = models.CharField(max_length=200, unique=True)
    celular = models.CharField(max_length=200, null=True)
    direccion = models.CharField(max_length=200, null=True)
    fecha_nacimiento = models.DateField()
    SEXOS = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    sexo = models.CharField(max_length=1,choices=SEXOS)
    DEPS = (
        ('A', 'Amazonas'),
        ('Caq', 'Caquetá'),
        ('Ca', 'Cauca'),
        ('H', 'Huila'),
        ('N', 'Nariño'),
        ('P', 'Putumayo'),
        ('T', 'Tolima'),
        ('VC', 'Valle del Cauca'),
    )
    departamento = models.CharField(max_length=3,choices=DEPS)
    ciudad = models.CharField(max_length=15)

    def __str__(self):
        return "%s" % (self.cedula)

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

class Usuario(AbstractBaseUser):
    id_persona = models.OneToOneField(Persona, verbose_name="Cédula de la persona")
    TIPOS = (
        ('1', 'Administrador'),
        ('2', 'Secretaria'),
        ('3', 'Master Teacher'),
        ('4', 'Leader Teacher')
    )
    tipo = models.CharField(max_length=1,choices=TIPOS)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = CierUserManager()
    USERNAME_FIELD = 'id_persona'
    REQUIRED_FIELDS = ['tipo']


    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.id_persona.nombre, self.id_persona.apellidos)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.id_persona.nombre

    def get_tipo(self):
        return self.tipo

    def __str__(self):
        return "%s" % (self.id_persona)

    def has_perm(self, perm, obj=None):
        # Por definir los permisos
        return True

    def has_module_perms(self, app_label):
        # Por definir los permisos de los modulos
        return True

    @property
    def is_staff(self):
        return self.is_admin

class Historial_Academico(models.Model):
    id_docente = models.ForeignKey(Persona, verbose_name="Cédula del docente")
    promocion = models.CharField(max_length=15)
    titulo = models.CharField(max_length=50)
    institucion = models.CharField(max_length=50)

    class Meta:
        unique_together = (("id_docente", "promocion","titulo","institucion"),)

    def __str__(self):
        return "%s - %s - %s. %s" % (self.id_docente, self.promocion, self.titulo, self.institucion)

    class Meta:
        verbose_name = "Historial Académico"
        verbose_name_plural = "Historiales Académicos"

class Historial_Laboral(models.Model):
    id_docente = models.ForeignKey(Persona,verbose_name="Cédula del docente")
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    institucion = models.CharField(max_length=50)

    class Meta:
        unique_together = (("id_docente", "fecha_inicio","fecha_fin","institucion"),)

    def __str__(self):
        return "%s - (%s)-(%s). %s" % (str(self.id_docente),str(self.fecha_inicio), str(self.fecha_fin), self.institucion)

    class Meta:
        verbose_name = "Historial Laboral"
        verbose_name_plural = "Historiales Laborales"

class Curso(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse("curso_detalle", kwargs={"slug": self.slug})
        
    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"

class Actividad(models.Model):
    id_curso = models.ForeignKey(Curso,verbose_name="Curso")
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=1000)
    porcentaje = models.FloatField()

    class Meta:
        unique_together = (("id_curso", "nombre"),)

    def __str__(self):
        return "%s - %s" % (str(self.id_curso), self.nombre)

    class Meta:
        verbose_name = "Actividad"
        verbose_name_plural = "Actividades"

class Cohorte(models.Model):
    id_curso = models.ForeignKey(Curso,verbose_name="Curso")
    semestre = models.CharField(max_length=50)

    def __str__(self):
        return "%s - %s-%s" % (str(self.id_curso), self.semestre, str(self.id))


class Posible_LT(models.Model):
    id_docente = models.ForeignKey(Persona,verbose_name="Cédula del docente")
    id_curso = models.ForeignKey(Curso,verbose_name="Curso")

    class Meta:
        unique_together = (("id_docente", "id_curso"),)

    def __str__(self):
        return "%s - %s" % (str(self.id_docente), str(self.id_curso))

    class Meta:
        verbose_name = "Posible LT"
        verbose_name_plural = "Posibles LT"


class LT_Curso(models.Model):
    id_lt = models.ForeignKey(Usuario,verbose_name="Cédula del docente")
    id_curso_cohorte = models.ForeignKey(Cohorte,verbose_name="Curso - Cohorte")
    fecha_inscripcion = models.DateField()
    aprobado =  models.NullBooleanField(default=None)
    class Meta:
        unique_together = (("id_lt", "id_curso_cohorte"),)

    def __str__(self):
        return "%s - %s" % (str(self.id_lt),str(self.id_curso_cohorte))

    def get_curso(self):
        return self.id_curso_cohorte.id_curso

    class Meta:
        verbose_name = "Curso-LT"
        verbose_name_plural = "Cursos-LT"


class MT_Curso(models.Model):
    id_mt = models.ForeignKey(Usuario,verbose_name="Cédula del docente")
    id_curso_cohorte = models.ForeignKey(Cohorte,verbose_name="Curso - Cohorte")

    class Meta:
        unique_together = (("id_mt", "id_curso_cohorte"),)

    def __str__(self):
        return "%s - %s" % (str(self.id_mt),str(self.id_curso_cohorte))


    class Meta:
        verbose_name = "Curso-MT"
        verbose_name_plural = "Cursos-MT"


class Nota(models.Model):
    id_lt_curso = models.ForeignKey(LT_Curso, verbose_name="LT-Curso")
    id_actividad = models.ForeignKey(Actividad,verbose_name="Actividad")
    calificacion = models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(5)])

    class Meta:
        unique_together = (("id_lt_curso", "id_actividad"),)

    def __str__(self):
        return "%s - %s - %s" % (str(self.id_lt_curso),str(self.id_actividad), str(self.calificacion))

    def set_calificacion(self,nota):
        if not (nota >= 0 and nota <=  5):
            raise IndexError('The note must be between 0 and 5')
        else:
            self.calificacion = nota

    class Meta:
        verbose_name = "Nota"
        verbose_name_plural = "Notas"        

class Certificado(models.Model):
    id_lt_curso = models.OneToOneField(LT_Curso, verbose_name="LT-Curso",primary_key=True)
    TIPOS = (
        ('A', 'Asistencia'),
        ('P', 'Participación'),
        ('E', 'Excelencia'),
    )
    tipo = models.CharField(max_length=1, choices=TIPOS)

    def __str__(self):
        return "%s - %s" % (str(self.id_lt_curso),str(self.tipo))

    class Meta:
        verbose_name = "Certificado"
        verbose_name_plural = "Certificados"

templates/reportes/reporte1.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Número de docentes estudiantes que han llegado en el mes de cada departamento - {{fecha}}</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="departamento">Departamento</th>
                                <th data-field="calificacion">No. de docentes estudiantes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in object_list.items %}
                            <tr> 
                                <td>{{key}}</td>
                                <td>{{value}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte2.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Cursos con mayor número de asistentes en el mes (Top 10)</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="posicion">Posición</th>
                                <th data-field="curso">Curso</th>
                                <th data-field="estudiantes">No. de estudiantes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in object_list %}
                                {% if forloop.counter < 11 %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte3.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Cursos con menos potencial de avance</p>
                        <p>Se listan los cursos que tengan un porcentaje de estudiantes reprobados mayor o igual al 50% a lo largo de todas las cohortes</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="posicion">Posición</th>
                                <th data-field="curso">Curso</th>
                                <th data-field="estudiantes">% Estudiantes reprobados</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in object_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte4.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Porcentaje de estudiantes que aprobaron los cursos de un semestre por departamento - Semestre: {{ semestre }} </p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="departamento">Departamento</th>
                                <th data-field="porcentajeAprobado">% Estudiantes aprobados</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in object_list.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte5.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Porcentaje de estudiantes que reprobaron los cursos de un semestre por departamento - Semestre: {{ semestre }} </p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="departamento">Departamento</th>
                                <th data-field="porcentajeAprobado">% Estudiantes reprobados</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in object_list.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte6.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Detalle del reporte de notas por estudiante</p>
                        <p><strong>Estudiante:</strong> {{ estudiante }}</p>
                        <p><strong>Curso:</strong> {{curso}}</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="id_actividad">Actividad</th>
                                <th data-field="calificacion">Calificación</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr> 
                                <td><a href="{% url 'actividad' pk=object.id_actividad.id %}">{{ object.id_actividad }}</a></td>
                                <td>{{ object.calificacion }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte7.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Histórico de estudiantes que hayan ganado un curso</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th data-field="id">id Estudiante</th>
                                <th data-field="nombre">Nombre del estudiante</th>
                                <th data-field="curso">Curso</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                                <tr>
                                    <td>{{ object.id_lt.id_persona.cedula }}</td>
                                    <td>{{ object.id_lt.get_full_name }}</td>
                                    <td>{{ object.id_curso_cohorte.id_curso.nombre }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte8.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Detalle de estudiantes en un curso por departamentos - Curso: {{ curso }}</p>
                    </div>
                    <div class="table-responsive">
                    <table class="table sortable">
                        <thead>
                            <tr>
                                <th data-field="id">id Estudiante</th>
                                <th data-field="nombre">Nombre del estudiante</th>
                                <th data-field="departamento">Curso</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                                <tr>
                                    <td>{{ object.id_lt.id_persona.cedula }}</td>
                                    <td>{{ object.id_lt.get_full_name }}</td>
                                    <td>{{ object.id_lt.id_persona.get_departamento_display }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reporte9.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<script type="text/javascript" src="{% static "js/Chart.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery-migrate-1.2.1.min.js" %}"></script>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reporte:</h1>
                        <p>Porcentaje de estudiantes que reprobaron los cursos de un semestre por departamento - Semestre: {{ semestre }} </p>
                    </div>
                    <canvas id="myChart" width="400" height="400"></canvas>
                    <script>
                    var ctx = $("#myChart").get(0).getContext("2d"); // This will get the first returned node in the jQuery collection. 

                    var data = { labels: {{lista_deps |safe}},
                                         datasets: [ { label: "My First dataset", 
                                              fillColor: "rgba(220,220,220,0.5)",
                                              strokeColor: "rgba(220,220,220,0.8)",
                                              highlightFill: "rgba(220,220,220,0.75)",
                                              highlightStroke: "rgba(220,220,220,1)",
                                              data: {{ lista_aprobados }} },

                                             { label: "My Second dataset",
                                               fillColor: "rgba(151,187,205,0.5)",
                                               strokeColor: "rgba(151,187,205,0.8)",
                                               highlightFill: "rgba(151,187,205,0.75)",
                                               highlightStroke: "rgba(151,187,205,1)",
                                               data: {{lista_reprobados}} }
                                           ] };

                    var myBarChart = new Chart(ctx).Bar(data);
                    </script>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reportes/reportes.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1>Reportes</h1>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{% url "reporte2" %}">Cursos con mayor número de asistentes en el mes (Top 10).</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte1" %}">Número de docentes estudiantes que han llegado en el mes de cada departamento.</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte3" %}">Cursos con menos potencial de avance.</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte4" %}">Porcentaje de estudiantes que aprobaron los cursos de un semestre por departamento</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte5" %}">Porcentaje de estudiantes que reprobaron los cursos de un semestre por departamento</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte6" %}">Detalle del reporte de notas por estudiante</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte7" %}">Histórico de estudiantes que hayan ganado un curso.</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte8" %}">Detalle de estudiantes en un curso por departamentos</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url "reporte9" %}">Porcentaje de aprobados y reprobados de un semestre por departamento</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}